name: Test and Deploy
on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout arrogan-node
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Publish to NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish --ignore-scripts